/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AppSettingSchema extends BaseModel {
  static $columns = ['key', 'updatedAt', 'value'] as const
  $columns = AppSettingSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}

export class CatalogProductSchema extends BaseModel {
  static $columns = ['active', 'category', 'costUsd', 'createdAt', 'description', 'formulaId', 'id', 'imagePath', 'minimumStock', 'name', 'previousSalePriceUsd', 'salePriceUsd', 'saleUnit', 'stockQuantity', 'updatedAt'] as const
  $columns = CatalogProductSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare category: string
  @column()
  declare costUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare formulaId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imagePath: string | null
  @column()
  declare minimumStock: string
  @column()
  declare name: string
  @column()
  declare previousSalePriceUsd: string | null
  @column()
  declare salePriceUsd: string
  @column()
  declare saleUnit: string
  @column()
  declare stockQuantity: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatalogProductSizeSchema extends BaseModel {
  static $columns = ['catalogProductId', 'createdAt', 'id', 'size', 'stockQuantity', 'updatedAt'] as const
  $columns = CatalogProductSizeSchema.$columns
  @column()
  declare catalogProductId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare size: string
  @column()
  declare stockQuantity: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'id', 'name', 'sortOrder', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CounterSchema extends BaseModel {
  static $columns = ['scope', 'updatedAt', 'value'] as const
  $columns = CounterSchema.$columns
  @column({ isPrimary: true })
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: number
}

export class CurrencySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'isActive', 'name', 'ratePerUsd', 'updatedAt'] as const
  $columns = CurrencySchema.$columns
  @column({ isPrimary: true })
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare ratePerUsd: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerPaymentSchema extends BaseModel {
  static $columns = ['accountId', 'amountUsd', 'createdAt', 'customerId', 'date', 'id', 'note', 'orderId', 'saleId', 'updatedAt'] as const
  $columns = CustomerPaymentSchema.$columns
  @column()
  declare accountId: bigint | number | null
  @column()
  declare amountUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: bigint | number
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare note: string | null
  @column()
  declare orderId: bigint | number | null
  @column()
  declare saleId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerSchema extends BaseModel {
  static $columns = ['active', 'address', 'createdAt', 'creditDays', 'document', 'email', 'id', 'imagePath', 'name', 'notes', 'phone', 'type', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditDays: number | null
  @column()
  declare document: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imagePath: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['accountId', 'amountUsd', 'createdAt', 'currencyCode', 'date', 'description', 'entryRate', 'id', 'updatedAt'] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare accountId: bigint | number | null
  @column()
  declare amountUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column.date()
  declare date: DateTime
  @column()
  declare description: string
  @column()
  declare entryRate: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class IncomeSchema extends BaseModel {
  static $columns = ['accountId', 'amountUsd', 'createdAt', 'currencyCode', 'date', 'description', 'entryRate', 'id', 'updatedAt'] as const
  $columns = IncomeSchema.$columns
  @column()
  declare accountId: bigint | number | null
  @column()
  declare amountUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column.date()
  declare date: DateTime
  @column()
  declare description: string
  @column()
  declare entryRate: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FormulaMaterialSchema extends BaseModel {
  static $columns = ['createdAt', 'formulaId', 'id', 'materialId', 'quantity', 'updatedAt'] as const
  $columns = FormulaMaterialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare formulaId: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare materialId: bigint | number
  @column()
  declare quantity: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FormulaSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = FormulaSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InventoryMovementSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'materialId', 'note', 'orderId', 'purchaseItemId', 'quantity', 'type'] as const
  $columns = InventoryMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare materialId: bigint | number
  @column()
  declare note: string | null
  @column()
  declare orderId: bigint | number | null
  @column()
  declare purchaseItemId: bigint | number | null
  @column()
  declare quantity: string
  @column()
  declare type: string
}

export class MachineExpenseSchema extends BaseModel {
  static $columns = ['accountId', 'amount', 'category', 'createdAt', 'currencyCode', 'date', 'description', 'id', 'machineId', 'notes', 'receiptFile', 'supplierId', 'updatedAt'] as const
  $columns = MachineExpenseSchema.$columns
  @column()
  declare accountId: bigint | number | null
  @column()
  declare amount: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column.date()
  declare date: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare machineId: bigint | number
  @column()
  declare notes: string | null
  @column()
  declare receiptFile: string | null
  @column()
  declare supplierId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MachineSchema extends BaseModel {
  static $columns = ['acquisitionCost', 'acquisitionDate', 'active', 'brand', 'createdAt', 'id', 'location', 'model', 'name', 'notes', 'serialNumber', 'status', 'type', 'updatedAt'] as const
  $columns = MachineSchema.$columns
  @column()
  declare acquisitionCost: string | null
  @column.date()
  declare acquisitionDate: DateTime | null
  @column()
  declare active: boolean
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare location: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare serialNumber: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaterialSchema extends BaseModel {
  static $columns = ['active', 'category', 'code', 'color', 'createdAt', 'defaultSupplierId', 'description', 'id', 'imagePath', 'lastPurchaseDate', 'lastPurchasePrice', 'lastPurchasePriceUsd', 'location', 'minimumStock', 'name', 'previousPurchasePriceUsd', 'previousSalePriceUsd', 'referenceCostUsd', 'referenceSalePriceUsd', 'salePriceUsd', 'supplierCode', 'unit', 'updatedAt'] as const
  $columns = MaterialSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare category: string
  @column()
  declare code: string
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultSupplierId: bigint | number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imagePath: string | null
  @column.date()
  declare lastPurchaseDate: DateTime | null
  @column()
  declare lastPurchasePrice: string | null
  @column()
  declare lastPurchasePriceUsd: string | null
  @column()
  declare location: string | null
  @column()
  declare minimumStock: string
  @column()
  declare name: string
  @column()
  declare previousPurchasePriceUsd: string | null
  @column()
  declare previousSalePriceUsd: string | null
  @column()
  declare referenceCostUsd: string | null
  @column()
  declare referenceSalePriceUsd: string | null
  @column()
  declare salePriceUsd: string | null
  @column()
  declare supplierCode: string | null
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderLineSchema extends BaseModel {
  static $columns = ['catalogProductId', 'catalogProductSizeId', 'costUsd', 'createdAt', 'id', 'notes', 'orderId', 'quantity', 'returnedQuantity', 'size', 'subtotalUsd', 'unitPriceUsd', 'updatedAt'] as const
  $columns = OrderLineSchema.$columns
  @column()
  declare catalogProductId: bigint | number
  @column()
  declare catalogProductSizeId: bigint | number | null
  @column()
  declare costUsd: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare notes: string | null
  @column()
  declare orderId: bigint | number
  @column()
  declare quantity: string
  @column()
  declare returnedQuantity: string
  @column()
  declare size: string | null
  @column()
  declare subtotalUsd: string
  @column()
  declare unitPriceUsd: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderMaterialSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'materialId', 'notes', 'orderId', 'quantityPerGarment', 'updatedAt'] as const
  $columns = OrderMaterialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare materialId: bigint | number
  @column()
  declare notes: string | null
  @column()
  declare orderId: bigint | number
  @column()
  declare quantityPerGarment: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderSchema extends BaseModel {
  static $columns = ['amountPaidUsd', 'balanceUsd', 'code', 'confirmedAt', 'createdAt', 'creditDueDate', 'customerId', 'description', 'estimatedDeliveryDate', 'guestName', 'id', 'modality', 'notes', 'orderDate', 'paymentType', 'referenceFile', 'returnedAt', 'status', 'totalPrice', 'totalQuantity', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column()
  declare amountPaidUsd: string
  @column()
  declare balanceUsd: string
  @column()
  declare code: string
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare creditDueDate: DateTime | null
  @column()
  declare customerId: bigint | number | null
  @column()
  declare description: string
  @column.date()
  declare estimatedDeliveryDate: DateTime | null
  @column()
  declare guestName: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare modality: string
  @column()
  declare notes: string | null
  @column.date()
  declare orderDate: DateTime
  @column()
  declare paymentType: string
  @column()
  declare referenceFile: string | null
  @column.dateTime()
  declare returnedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalPrice: string | null
  @column()
  declare totalQuantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentMethodSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'currencyCode', 'id', 'isActive', 'name', 'sortOrder', 'updatedAt'] as const
  $columns = PaymentMethodSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductInventoryMovementSchema extends BaseModel {
  static $columns = ['catalogProductId', 'createdAt', 'createdByUserId', 'id', 'note', 'orderId', 'purchaseItemId', 'quantity', 'saleId', 'type'] as const
  $columns = ProductInventoryMovementSchema.$columns
  @column()
  declare catalogProductId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: bigint | number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare note: string | null
  @column()
  declare orderId: bigint | number | null
  @column()
  declare purchaseItemId: bigint | number | null
  @column()
  declare quantity: string
  @column()
  declare saleId: bigint | number | null
  @column()
  declare type: string
}

export class PurchaseItemSchema extends BaseModel {
  static $columns = ['catalogProductId', 'createdAt', 'id', 'materialId', 'purchaseId', 'quantity', 'subtotalBs', 'subtotalUsd', 'unitPriceBs', 'unitPriceUsd', 'updatedAt'] as const
  $columns = PurchaseItemSchema.$columns
  @column()
  declare catalogProductId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare materialId: bigint | number | null
  @column()
  declare purchaseId: bigint | number
  @column()
  declare quantity: string
  @column()
  declare subtotalBs: string
  @column()
  declare subtotalUsd: string | null
  @column()
  declare unitPriceBs: string
  @column()
  declare unitPriceUsd: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchaseSchema extends BaseModel {
  static $columns = ['accountId', 'amountPaidUsd', 'balanceUsd', 'createdAt', 'creditDueDate', 'date', 'entryCurrencyCode', 'id', 'invoiceFile', 'invoiceNumber', 'isCredit', 'notes', 'receivedDate', 'status', 'supplierId', 'totalBs', 'totalUsd', 'updatedAt', 'usdRate', 'voidedAt'] as const
  $columns = PurchaseSchema.$columns
  @column()
  declare accountId: bigint | number | null
  @column()
  declare amountPaidUsd: string
  @column()
  declare balanceUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare creditDueDate: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare entryCurrencyCode: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare invoiceFile: string | null
  @column()
  declare invoiceNumber: string | null
  @column()
  declare isCredit: boolean
  @column()
  declare notes: string | null
  @column.date()
  declare receivedDate: DateTime | null
  @column()
  declare status: string
  @column()
  declare supplierId: bigint | number | null
  @column()
  declare totalBs: string
  @column()
  declare totalUsd: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usdRate: string | null
  @column.dateTime()
  declare voidedAt: DateTime | null
}

export class SaleLineMaterialSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'materialId', 'quantityPerUnit', 'saleLineId', 'updatedAt'] as const
  $columns = SaleLineMaterialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare materialId: bigint | number
  @column()
  declare quantityPerUnit: string
  @column()
  declare saleLineId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SaleLineSchema extends BaseModel {
  static $columns = ['catalogProductId', 'catalogProductSizeId', 'costUsd', 'createdAt', 'description', 'id', 'kitchenNote', 'materialId', 'quantity', 'returnedQuantity', 'saleId', 'size', 'subtotalUsd', 'unitPriceUsd', 'updatedAt'] as const
  $columns = SaleLineSchema.$columns
  @column()
  declare catalogProductId: bigint | number | null
  @column()
  declare catalogProductSizeId: bigint | number | null
  @column()
  declare costUsd: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare kitchenNote: string | null
  @column()
  declare materialId: bigint | number | null
  @column()
  declare quantity: string
  @column()
  declare returnedQuantity: string
  @column()
  declare saleId: bigint | number
  @column()
  declare size: string | null
  @column()
  declare subtotalUsd: string
  @column()
  declare unitPriceUsd: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SalesShiftSchema extends BaseModel {
  static $columns = ['closedAt', 'closedByUserId', 'createdAt', 'id', 'notes', 'openedAt', 'openedByUserId', 'status', 'updatedAt'] as const
  $columns = SalesShiftSchema.$columns
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare closedByUserId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare notes: string | null
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare openedByUserId: bigint | number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SaleSchema extends BaseModel {
  static $columns = ['amountPaidUsd', 'balanceUsd', 'billingMode', 'code', 'confirmedAt', 'createdAt', 'creditDueDate', 'customerId', 'discountUsd', 'guestName', 'id', 'orderStatus', 'paymentMethodCode', 'paymentType', 'returnedAt', 'salesShiftId', 'soldAt', 'soldByUserId', 'status', 'totalBs', 'totalUsd', 'updatedAt', 'usdRate'] as const
  $columns = SaleSchema.$columns
  @column()
  declare amountPaidUsd: string
  @column()
  declare balanceUsd: string
  @column()
  declare billingMode: string
  @column()
  declare code: string | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare creditDueDate: DateTime | null
  @column()
  declare customerId: bigint | number | null
  @column()
  declare discountUsd: string
  @column()
  declare guestName: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare orderStatus: string
  @column()
  declare paymentMethodCode: string | null
  @column()
  declare paymentType: string
  @column.dateTime()
  declare returnedAt: DateTime | null
  @column()
  declare salesShiftId: bigint | number | null
  @column.dateTime()
  declare soldAt: DateTime | null
  @column()
  declare soldByUserId: bigint | number | null
  @column()
  declare status: string
  @column()
  declare totalBs: string | null
  @column()
  declare totalUsd: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usdRate: string | null
}

export class SupplierPaymentSchema extends BaseModel {
  static $columns = ['accountId', 'amountUsd', 'createdAt', 'date', 'id', 'note', 'purchaseId', 'supplierId', 'updatedAt'] as const
  $columns = SupplierPaymentSchema.$columns
  @column()
  declare accountId: bigint | number | null
  @column()
  declare amountUsd: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare note: string | null
  @column()
  declare purchaseId: bigint | number | null
  @column()
  declare supplierId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SupplierSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'creditDays', 'email', 'id', 'imagePath', 'name', 'notes', 'phone', 'rif', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditDays: number | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare imagePath: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare rif: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'email', 'id', 'name', 'password', 'permissions', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare permissions: any | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
